{% set version = "0.11.0" %}

package:
  name: pika
  version: {{ version }}

source:
  fn: pika-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pika/pika-{{ version }}.tar.gz
  sha256: b87fd6b339450f531b8cba3bc02d8448cab15798032c02b7601367d09abc3818

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pika

about:
  home: http://pika.readthedocs.org
  license: BSD 3-clause
  summary: Pure Python RabbitMQ/AMQP 0-9-1 client library

extra:
  recipe-maintainers:
    - frol
